[functions]
  included_files = ["netlify/functions/documents/**"]

[build]
  command = "if [ \"$IS_PRODUCTION\" != 'true' ]; then echo 'User-agent: *' > robots.txt && echo 'Disallow: /' >> robots.txt; fi"
  publish = "."